[build-system]
requires = ["uv_build >= 0.10.10, <0.11.0"]
build-backend = "uv_build"

[project]
name = "mytestrepo_py_gucio321"
version = "0.0.2-alpha.2"
authors = [
  { name="M. Sz.", email="gucio321@protonmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/gucio321/mytestrepo-py"
Issues = "https://github.com/gucio321/mytestrepo-py/issues"
